---
sudo: false
language: python
python:
  - "3.5"
  - "3.8"

matrix:
  fast_finish: true

env:
  - PIPENV_VERBOSITY=-1

install:
  # - pip install pipenv  # is already installed on Travis CI
  - pipenv install --dev

script:
  - pylint promgen_k8s
  - pytest
