---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
  - cron: '45 4 * * 4'  # weekly on thursday morning

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.5'
        - '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Lint
      run: |
        poetry run yapf -q -r promgen_k8s
        poetry run pylint --ignore=snapshots promgen_k8s tests
        poetry run mypy promgen_k8s
    - name: Test
      run: |
        poetry run pytest
